plugins {
    java
    id("io.quarkus")
}

repositories {
    mavenCentral()
    mavenLocal()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:quarkus-camel-bom:${quarkusPlatformVersion}"))
    implementation("org.apache.camel.quarkus:camel-quarkus-slack")
    implementation("io.quarkus:quarkus-oidc-client")
    implementation("io.quarkus:quarkus-oidc-client-reactive-filter")
    implementation("org.apache.camel.quarkus:camel-quarkus-quartz")
    implementation("io.quarkus:quarkus-smallrye-jwt")
    implementation("io.quarkiverse.poi:quarkus-poi:2.0.0")
    implementation("io.quarkiverse.dashbuilder:quarkus-dashbuilder:0.27.0")
    implementation("io.quarkus:quarkus-opentelemetry")
    implementation("org.apache.camel.quarkus:camel-quarkus-jdbc")
    implementation("io.quarkus:quarkus-minikube")
    implementation("io.quarkus:quarkus-hibernate-reactive-panache")
    implementation("io.quarkus:quarkus-container-image-docker")
    implementation("io.quarkus:quarkus-rest-client")
    implementation("io.quarkus:quarkus-keycloak-admin-client")
    implementation("io.quarkus:quarkus-avro")
    implementation("org.apache.camel.quarkus:camel-quarkus-ical")
    implementation("io.quarkus:quarkus-kubernetes-service-binding")
    implementation("io.quarkiverse.operatorsdk:quarkus-operator-sdk-bundle-generator:6.0.0.CR1")
    implementation("io.quarkus:quarkus-hibernate-reactive-rest-data-panache")
    implementation("org.apache.camel.quarkus:camel-quarkus-gson")
    implementation("io.quarkus:quarkus-kubernetes")
    implementation("io.quarkus:quarkus-grpc")
    implementation("org.apache.camel.quarkus:camel-quarkus-kafka")
    implementation("org.apache.camel.quarkus:camel-quarkus-bean-validator")
    implementation("org.apache.camel.quarkus:camel-quarkus-microprofile-health")
    implementation("io.quarkus:quarkus-narayana-stm")
    implementation("io.quarkus:quarkus-liquibase")
    implementation("org.apache.camel.quarkus:camel-quarkus-micrometer")
    implementation("io.quarkus:quarkus-kubernetes-config")
    implementation("io.quarkus:quarkus-cache")
    implementation("org.apache.camel.quarkus:camel-quarkus-pdf")
    implementation("org.apache.camel.quarkus:camel-quarkus-grpc")
    implementation("io.quarkiverse.loggingsentry:quarkus-logging-sentry:2.0.0")
    implementation("org.apache.camel.quarkus:camel-quarkus-minio")
    implementation("io.quarkus:quarkus-smallrye-fault-tolerance")
    implementation("io.quarkus:quarkus-scheduler")
    implementation("org.apache.camel.quarkus:camel-quarkus-debezium-postgres")
    implementation("io.quarkus:quarkus-container-image-jib")
    implementation("io.quarkus:quarkus-smallrye-stork")
    implementation("org.apache.camel.quarkus:camel-quarkus-csv")
    implementation("org.apache.camel.quarkus:camel-quarkus-jackson-avro")
    implementation("org.apache.camel.quarkus:camel-quarkus-file-watch")
    implementation("io.quarkus:quarkus-hibernate-orm-panache")
    implementation("io.quarkus:quarkus-oidc-token-propagation")
    implementation("org.apache.camel.quarkus:camel-quarkus-knative")
    implementation("io.quarkus:quarkus-reactive-routes")
    implementation("io.quarkus:quarkus-rest-client-reactive")
    implementation("io.quarkiverse.operatorsdk:quarkus-operator-sdk:6.0.0.CR1")
    implementation("org.apache.camel.quarkus:camel-quarkus-consul")
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-oidc-client-filter")
    implementation("org.apache.camel.quarkus:camel-quarkus-avro")
    implementation("org.apache.camel.quarkus:camel-quarkus-caffeine")
    implementation("io.quarkus:quarkus-logging-json")
    implementation("io.quarkus:quarkus-oidc-token-propagation-reactive")
    implementation("io.quarkus:quarkus-hibernate-orm-rest-data-panache")
    implementation("io.quarkus:quarkus-elasticsearch-java-client")
    implementation("io.quarkus:quarkus-micrometer-registry-prometheus")
    implementation("io.quarkus:quarkus-hibernate-validator")
    implementation("io.quarkus:quarkus-logging-gelf")
    implementation("org.apache.camel.quarkus:camel-quarkus-kubernetes")
    implementation("io.quarkus:quarkus-csrf-reactive")
    implementation("io.quarkus:quarkus-jackson")
    implementation("org.apache.camel.quarkus:camel-quarkus-jta")
    implementation("io.quarkus:quarkus-qute")
    implementation("io.quarkus:quarkus-kind")
    implementation("io.quarkus:quarkus-elasticsearch-rest-client")
    implementation("org.apache.camel.quarkus:camel-quarkus-microprofile-fault-tolerance")
    implementation("io.quarkus:quarkus-rest-client-reactive-jackson")
    implementation("io.quarkus:quarkus-jdbc-postgresql")
    implementation("io.quarkiverse.jackson-jq:quarkus-jackson-jq:2.0.0.Alpha")
    implementation("io.quarkus:quarkus-keycloak-authorization")
    implementation("io.quarkus:quarkus-confluent-registry-avro")
    implementation("io.quarkus:quarkus-kubernetes-client")
    implementation("io.quarkus:quarkus-jacoco")
    implementation("io.quarkus:quarkus-mailer")
    implementation("io.quarkus:quarkus-keycloak-admin-client-reactive")
    implementation("io.quarkus:quarkus-hibernate-reactive")
    implementation("io.quarkus:quarkus-info")
    implementation("org.apache.camel.quarkus:camel-quarkus-jackson")
    implementation("io.quarkiverse.vault:quarkus-vault")
    implementation("org.apache.camel.quarkus:camel-quarkus-json-validator")
    implementation("io.quarkus:quarkus-smallrye-context-propagation")
    implementation("org.apache.camel.quarkus:camel-quarkus-opentelemetry")
    implementation("org.apache.camel.quarkus:camel-quarkus-reactive-executor")
    implementation("io.quarkiverse.helm:quarkus-helm:1.0.3")
    implementation("io.quarkus:quarkus-rest-client-jackson")
    implementation("io.quarkus:quarkus-smallrye-reactive-messaging")
    implementation("io.quarkus:quarkus-quartz")
    implementation("io.quarkus:quarkus-redis-cache")
    implementation("io.quarkus:quarkus-redis-client")
    implementation("org.apache.camel.quarkus:camel-quarkus-zipfile")
    implementation("io.quarkus:quarkus-smallrye-jwt-build")
    implementation("io.quarkus:quarkus-resteasy-jaxb")
    implementation("org.apache.camel.quarkus:camel-quarkus-lra")
    implementation("io.quarkus:quarkus-narayana-lra")
    implementation("org.apache.camel.quarkus:camel-quarkus-debezium-sqlserver")
    implementation("org.apache.camel.quarkus:camel-quarkus-jsonpath")
    implementation("org.apache.camel.quarkus:camel-quarkus-jira")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-picocli")
    implementation("io.quarkus:quarkus-smallrye-reactive-messaging-kafka")
    implementation("io.quarkus:quarkus-kafka-streams")
    implementation("org.apache.camel.quarkus:camel-quarkus-mail")
    implementation("org.apache.camel.quarkus:camel-quarkus-reactive-streams")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("org.apache.camel.quarkus:camel-quarkus-cassandraql")
    implementation("org.apache.camel.quarkus:camel-quarkus-file")
    implementation("io.quarkus:quarkus-resteasy-reactive-links")
    implementation("io.quarkus:quarkus-kafka-client")
    implementation("io.quarkiverse.config:quarkus-config-consul:2.0.0")
    implementation("io.quarkiverse.tika:quarkus-tika:2.0.0.CR1")
    implementation("org.apache.camel.quarkus:camel-quarkus-bean")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("io.quarkus:quarkus-resteasy-links")
    implementation("io.quarkus:quarkus-micrometer")
    implementation("org.apache.camel.quarkus:camel-quarkus-exec")
    implementation("org.apache.camel.quarkus:camel-quarkus-jslt")
    implementation("io.quarkus:quarkus-oidc")
    implementation("org.apache.camel.quarkus:camel-quarkus-protobuf")
    implementation("org.apache.camel.quarkus:camel-quarkus-zip-deflater")
    implementation("io.quarkus:quarkus-security-jpa")
    implementation("io.quarkiverse.itext:quarkus-itext:3.0.2")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-hibernate-orm")
    implementation("io.quarkus:quarkus-resteasy")
    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.rest-assured:rest-assured")
}

group = "org.acme"
version = "1.0.0-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<Test> {
    systemProperty("java.util.logging.manager", "org.jboss.logmanager.LogManager")
}
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}
